export const possibleLanguages = [
  "  ADLaM",
  "Albanian",
  "Arabic (101)",
  "Arabic (102)",
  "Arabic (102) AZERTY",
  "Armenian Eastern (Legacy)",
  "Armenian Phonetic",
  "Armenian Typewriter",
  "Armenian Western (Legacy)",
  "Assamese - INSCRIPT",
  "Azerbaijani (Standard)",
  "Azerbaijani Cyrillic",
  "Azerbaijani Latin",
  "Bangla",
  "Bangla - INSCRIPT",
  "Bangla - INSCRIPT (Legacy)",
  "Bashkir",
  "Belarusian",
  "Belgian (Comma)",
  "Belgian (Period)",
  "Belgian French",
  "Bosnian (Cyrillic)",
  "Buginese",
  "Bulgarian",
  "Bulgarian (Latin)",
  "Bulgarian (Phonetic Traditional)",
  "Bulgarian (Phonetic)",
  "Bulgarian (Typewriter)",
  "Canadian French",
  "Canadian French (Legacy)",
  "Canadian Multilingual Standard",
  "Central Atlas Tamazight",
  "Central Kurdish",
  "Czech",
  "Czech (QWERTY)",
  "Czech Programmers",
  "Danish",
  "Devanagari - INSCRIPT",
  "Divehi Phonetic",
  "Divehi Typewriter",
  "Dutch",
  "Dzongkha",
  "English (India)",
  "Estonian",
  "Faeroese",
  "Finnish",
  "Finnish with Sami",
  "French",
  "Futhark",
  "Georgian (Ergonomic)",
  "Georgian (Legacy)",
  "Georgian (MES)",
  "Georgian (Old Alphabets)",
  "Georgian (QWERTY)",
  "German",
  "German (IBM)",
  "Gothic",
  "Greek",
  "Greek (220)",
  "Greek (220) Latin",
  "Greek (319)",
  "Greek (319) Latin",
  "Greek Latin",
  "Greek Polytonic",
  "Greenlandic",
  "Guarani",
  "Gujarati",
  "Hausa",
  "Hawaiian",
  "Hebrew",
  "Hebrew (Standard)",
  "Hindi Traditional",
  "Hungarian",
  "Hungarian 101-key",
  "Cherokee Nation",
  "Cherokee Phonetic",
  "Chinese (Simplified) - US",
  "Chinese (Simplified, Singapore) - US",
  "Chinese (Traditional) - US",
  "Chinese (Traditional, Hong Kong S.A.R.) - US",
  "Chinese (Traditional, Macao S.A.R.) - US",
  "Icelandic",
  "Igbo",
  "Inuktitut - Latin",
  "Inuktitut - Naqittaut",
  "Irish",
  "Italian",
  "Italian (142)",
  "Japanese",
  "Javanese",
  "Kannada",
  "Kazakh",
  "Khmer",
  "Khmer (NIDA)",
  "Korean",
  "Kyrgyz Cyrillic",
  "Lao",
  "Latin American",
  "Latvian",
  "Latvian (QWERTY)",
  "Latvian (Standard)",
  "Lisu (Basic)",
  "Lisu (Standard)",
  "Lithuanian",
  "Lithuanian IBM",
  "Lithuanian Standard",
  "Luxembourgish",
  "Macedonian",
  "Macedonian - Standard",
  "Malayalam",
  "Maltese 47-Key",
  "Maltese 48-Key",
  "Maori",
  "Marathi",
  "Mongolian (Mongolian Script)",
  "Mongolian Cyrillic",
  "Myanmar (Phonetic order)",
  "Myanmar (Visual order)",
  "N’Ko",
  "Nepali",
  "New Tai Lue",
  "Norwegian",
  "Norwegian with Sami",
  "NZ Aotearoa",
  "Odia",
  "Ogham",
  "Ol Chiki",
  "Old Italic",
  "Osage",
  "Osmanya",
  "Pashto (Afghanistan)",
  "Persian",
  "Persian (Standard)",
  "Phags-pa",
  "Polish (214)",
  "Polish (Programmers)",
  "Portuguese",
  "Portuguese (Brazil ABNT)",
  "Portuguese (Brazil ABNT2)",
  "Punjabi",
  "Romanian (Legacy)",
  "Romanian (Programmers)",
  "Romanian (Standard)",
  "Russian",
  "Russian - Mnemonic",
  "Russian (Typewriter)",
  "Sakha",
  "Sami Extended Finland-Sweden",
  "Sami Extended Norway",
  "Scottish Gaelic",
  "Serbian (Cyrillic)",
  "Serbian (Latin)",
  "Sesotho sa Leboa",
  "Setswana",
  "Sinhala",
  "Sinhala - Wij 9",
  "Slovak",
  "Slovak (QWERTY)",
  "Slovenian",
  "Sora",
  "Sorbian Extended",
  "Sorbian Standard",
  "Sorbian Standard (Legacy)",
  "Spanish",
  "Spanish Variation",
  "Standard",
  "Swedish",
  "Swedish with Sami",
  "Swiss French",
  "Swiss German",
  "Syriac",
  "Syriac Phonetic",
  "Tai Le",
  "Tajik",
  "Tamil",
  "Tamil 99",
  "Tatar",
  "Tatar (Legacy)",
  "Telugu",
  "Thai Kedmanee",
  "Thai Kedmanee (non-ShiftLock)",
  "Thai Pattachote",
  "Thai Pattachote (non-ShiftLock)",
  "Tibetan (PRC)",
  "Tibetan (PRC) - Updated",
  "Tifinagh (Basic)",
  "Tifinagh (Extended)",
  "Traditional Mongolian (Standard)",
  "Turkish F",
  "Turkish Q",
  "Turkmen",
  "Ukrainian",
  "Ukrainian (Enhanced)",
  "United Kingdom",
  "United Kingdom Extended",
  "United States-Dvorak",
  "United States-Dvorak for left hand",
  "United States-Dvorak for right hand",
  "United States-International",
  "Urdu",
  "US",
  "US English Table for IBM Arabic 238_L",
  "Uyghur",
  "Uyghur (Legacy)",
  "Uzbek Cyrillic",
  "Vietnamese",
  "Wolof",
  "Yoruba",
] as const;

export type Language = typeof possibleLanguages[number];

export const isLanguage = (lang: string): lang is Language =>
  possibleLanguages.includes(lang as Language);
